# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  infnetdevops23e33dockerproject-dev:
    image: alexfariakof/infnet-devops-project-dev
    build:
      context: .
      dockerfile: Infnet_DevOps_23E3_3_Docker_Project/Dockerfile-Development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - 42536:80