#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 42536

ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Infnet_DevOps_23E3_3_Docker_Project/Infnet_DevOps_23E3_3_Docker_Project.csproj", "Infnet_DevOps_23E3_3_Docker_Project/"]
COPY ["Infnet_DevOps_23E3_3_Docker_Project_Test/Infnet_DevOps_23E3_3_Docker_Project_Test.csproj", "Infnet_DevOps_23E3_3_Docker_Project_Test/"]
RUN dotnet restore "Infnet_DevOps_23E3_3_Docker_Project/Infnet_DevOps_23E3_3_Docker_Project.csproj"
COPY . .
WORKDIR "/src/Infnet_DevOps_23E3_3_Docker_Project"
RUN dotnet build "Infnet_DevOps_23E3_3_Docker_Project.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Infnet_DevOps_23E3_3_Docker_Project.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Infnet_DevOps_23E3_3_Docker_Project.dll"]